version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo
    networks:
        - volo
    volumes:
        - mongodata:C:/data/db

  volo-opcua-server:
    image: volo-opcua-server
    container_name: volo-opcua-server
    networks:
        - volo
    ports:
        - "7718:7718"
    depends_on: 
        - mongodb

  volo-controller:
    image: volo-controller
    container_name: volo-controller
    networks:
      - volo
    depends_on: 
      - volo-opcua-server

  volo-api:
    image: volo-api
    container_name: volo-api
    networks:
        - volo
    ports:
        - "5000:80"
    depends_on: 
        - volo-controller

volumes:
    mongodata:

networks:
    volo:
        name: volo
        driver: nat